[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_DISABLE_SWC_NATIVE_USAGE = "1"
  NEXT_TELEMETRY_DISABLED = "1"

[[plugins]]
  package = "@netlify/plugin-nextjs"